version: '3.8'

services:

  db:
    container_name: postgresql_db #will be donloaded from docker hub
    image: postgres
    restart: always # important if the database fails so it can restarts
    ports:
      - 5432:5432 # the port of the container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
      
  app:
    container_name: app
    # using dot means the directory
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    # command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/aftermath 
    ports:
      - 8000:8000
      # depends on the database
    depends_on:
      - db
    restart: always



